services:
  api:
    build:
      dockerfile: ./Dockerfile
      args:
        CMD: api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres:5432
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
      HTTP_ADDRESS: "${HTTP_ADDRESS}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  publisher:
    build:
      dockerfile: ./Dockerfile
      args:
        CMD: publisher
    environment:
      DB_HOST: postgres:5432
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
      HTTP_ADDRESS: "${HTTP_ADDRESS}"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  dispatcher:
    build:
      dockerfile: ./Dockerfile
      args:
        CMD: dispatcher
    environment:
      DB_HOST: postgres:5432
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
      HTTP_ADDRESS: "${HTTP_ADDRESS}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./internal/database/migration:/migrations:ro
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?sslmode=disable",
        "up"
      ]

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://${KAFKA_BROKERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-ui:
    image: kafbat/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  db-data:
  kafka-data: